# docker-compose.yml

version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: sooft_tech_db
      POSTGRES_USER: sooft_user
      POSTGRES_PASSWORD: sooft_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sooft_user -d sooft_tech_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: